# Generated by Django 3.2.13 on 2022-05-02 15:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='media/uploads/'),
        ),
    ]
