# Generated by Django 3.2.13 on 2022-05-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_articlepost_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
