# Generated by Django 3.2.13 on 2022-05-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_articlepost_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='image',
            field=models.ImageField(upload_to='media/uploads/'),
        ),
    ]
